flags: {}
packages: []
extra-deps:
  # For ghc-mod (0.5.4)
  - cabal-helper-0.6.0.0
  # For fltk
  - fltkhs-fluid-examples-0.0.0.1
  - fltkhs-0.1.0.2
  # For hscope-0.4.2
  - pure-cdb-0.1.1
resolver: lts-3.15

